// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CKGen.Temp.DataAccess.CodeTempletes
{
    using CKGen.DBSchema;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class TableSchemaTemplete : TableSchemaTempleteBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Syste" +
                    "m.Data.SqlClient;\r\nusing zlab.ORM.Schema;\r\n\r\nnamespace ");
            
            #line 11 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpace));
            
            #line default
            #line hidden
            this.Write(".Schema\r\n{\r\n\t[Serializable]\r\n\tpublic sealed class ");
            
            #line 14 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DBTable.Name));
            
            #line default
            #line hidden
            this.Write(@"Schema
	{
		public static List<ColumnSchema> Columns = new List<ColumnSchema>();
		
		public static SqlParameter GetSqlParameter(string colName)
		{
			ColumnSchema cSchema = null;
			foreach(ColumnSchema item in Columns)
			{
				if(item.Name == colName || item.RawName == colName)
				{
					cSchema = item;
					break;
				}
			}
			if(cSchema != null)
				return cSchema.GetSqlParameter();
			return null;
		}
		
");
            
            #line 34 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"

	    foreach (var column in DBTable.Columns)
	    {
			string colName = "_" + column.CamelName;
			string ColName = column.PascalName;
			string sqlType = column.DBType;
			string csharpType = column.LanguageType;
			string desc = column.Description;

            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n        /// ");
            
            #line 44 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Description));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n\t\tpublic static ColumnSchema ");
            
            #line 46 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.PascalName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\r\n");
            
            #line 48 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
 
		}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tstatic ");
            
            #line 52 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DBTable.Name));
            
            #line default
            #line hidden
            this.Write("Schema()\r\n\t\t{\r\n");
            
            #line 54 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"

	    foreach (var column in DBTable.Columns)
	    {
			string ColName = column.PascalName;
			string nullable = column.Nullable ? "true" : "false";
			string isPrimaryKey = column.IsPrimaryKey ? "true" : "false";

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 61 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(" = new ColumnSchema();\r\n\t\t\t");
            
            #line 62 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".Name = \"");
            
            #line 62 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t");
            
            #line 63 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".RawName = \"");
            
            #line 63 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.RawName));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t");
            
            #line 64 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".DBType = \"");
            
            #line 64 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.DBType));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t");
            
            #line 65 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".SqlDataType = \"");
            
            #line 65 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.DbTargetType));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t");
            
            #line 66 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".Nullable = ");
            
            #line 66 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nullable));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 67 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".MaxLength = ");
            
            #line 67 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.MaxLength));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 68 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
 if(LanguageConvert.IsNumericType(column.DBType)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 69 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".Precision = ");
            
            #line 69 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Precision));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 70 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".Scale = ");
            
            #line 70 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Scale));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 71 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t");
            
            #line 72 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".IsPrimaryKey = ");
            
            #line 72 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrimaryKey));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 73 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(".Description = \"");
            
            #line 73 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Description));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t\r\n\t\t\tColumns.Add(");
            
            #line 75 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColName));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\r\n\t\t\t\r\n");
            
            #line 78 "D:\zhhcode\CKGen\CKGen\CKGen.Temp.DataAccess\CodeTempletes\TableSchemaTemplete.tt"
 
		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class TableSchemaTempleteBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
